s=set()
p = input("enter your num:")
s.add(int(p))
p = input("enter your num:")
s.add(int(p))
p = input("enter your num:")
s.add(int(p))
p = input("enter your num:")
s.add(int(p))
p = input("enter your num:")
s.add(int(p))
p = input("enter your num:")
s.add(int(p))
p = input("enter your num:")
s.add(int(p))
print(s)